SistemaRegistrodeCamarasParticulares/Controllers/CasaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaRegistrodeCamarasParticulares.Context;
using SistemaRegistrodeCamarasParticulares.Models;
using System.IO;

namespace SistemaRegistrodeCamarasParticulares.Controllers
{
    [Authorize(Roles = "Particular")]
    public class CasaController : Controller
    {
        private readonly DbRegistroCamarasParticularesContext _context;

        public CasaController(DbRegistroCamarasParticularesContext context)
        {
            _context = context;
        }

        // GET: Casa
        public async Task<IActionResult> Index()
        {
            var dbRegistroCamarasParticularesContext = _context.Casas.Include(c => c.IdUsuarioNavigation);
            return View(await dbRegistroCamarasParticularesContext.ToListAsync());
        }

        // GET: Casa/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var casa = await _context.Casas
                .Include(c => c.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (casa == null)
            {
                return NotFound();
            }

            return View(casa);
        }

        // GET: Casa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Casa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection coleccion, [Bind("Id,IdUsuario,TipoCasa,Descripcion,Municipio,Colonia,CallePrincipal,CalleSecundaria,CalleTercera," +
            "CodigoPostal,NumeroExterior,NumeroInterior,NumCamsFijas,NumCamsMoviles,Componentes,TiempoGrabacion,Latitud,Longitud")] Casa casa)
        {
            if (ModelState.IsValid)
            {
                string path = coleccion["archivos"];
                if (string.IsNullOrEmpty(path))
                {
                    TempData["Error"] = "Debe cargar el comprobante de domicilio de la casa.";
                    return View(casa);
                }

                casa.CreatedAt = DateTime.Now;
                casa.UpdatedAt = DateTime.Now;
                _context.Add(casa);
                await _context.SaveChangesAsync();


                //obtener documento de la carpeta documentos
                string contenido = System.IO.File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", path.TrimStart('/')));
                byte[] documentoBytes = System.Text.Encoding.UTF8.GetBytes(contenido);


                var documento = new Documento
                {
                    Id = Guid.NewGuid(),
                    Tipo = "Domicilio",
                    IdUsuario = casa.IdUsuario,
                    IdCasa = casa.Id,
                    Documento1 = documentoBytes,
                    Ruta = path,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };
                
                _context.Add(documento);

                //borrar archivo de la carpeta documentos
                System.IO.File.Delete(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", path.TrimStart('/')));

                await _context.SaveChangesAsync();
                TempData["Success"] = "Casa registrada correctamente.";
                return RedirectToAction(nameof(Index));
            }
            //ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "Id", "Id", casa.IdUsuario);
            TempData["Error"] = "Error al registrar la Casa, verifique la información e intentelo de nuevo";
            return View(casa);
        }

        // GET: Casa/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var casa = await _context.Casas.FindAsync(id);
            if (casa == null)
            {
                return NotFound();
            }
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "Id", "Id", casa.IdUsuario);
            return View(casa);
        }

        // POST: Casa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,IdUsuario,Descripcion,Municipio,Colonia,CallePrincipal,CalleSecundaria,CalleTercera,CodigoPostal,NumeroExterior,NumeroInterior,Latitud,Longitud,CreatedAt,UpdatedAt,DeletedAt")] Casa casa)
        {
            if (id != casa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(casa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CasaExists(casa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "Id", "Id", casa.IdUsuario);
            return View(casa);
        }

        // GET: Casa/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var casa = await _context.Casas
                .Include(c => c.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (casa == null)
            {
                return NotFound();
            }

            return View(casa);
        }

        // POST: Casa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var casa = await _context.Casas.FindAsync(id);
            if (casa != null)
            {
                _context.Casas.Remove(casa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CasaExists(long id)
        {
            return _context.Casas.Any(e => e.Id == id);
        }
    }
}

SistemaRegistrodeCamarasParticulares/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewData["Title"] - Sistema Estatal de Video Vigilancia para Particulares</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link rel="icon"
          href="~/img/logos/LOGO-SSPE.png"
          type="image/x-icon" />

    <!-- Fonts and icons -->
    <script src="~/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
          google: { families: ["Public Sans:300,400,500,600,700"] },
          custom: {
            families: [
              "Font Awesome 5 Solid",
              "Font Awesome 5 Regular",
              "Font Awesome 5 Brands",
              "simple-line-icons",
            ],
            urls: ["/css/fonts.min.css"],
          },
          active: function () {
            sessionStorage.fonts = true;
          },
        });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/plugins.min.css" />
    <link rel="stylesheet" href="~/css/kaiadmin.min.css" />
    <style>
        .nav-collapse .sub-item {
            color: white !important;
        }

        .profile-username{
            color: white !important;
        }
    </style>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <div class="sidebar" style="background-color:#611232">
            <div class="sidebar-logo">
                <!-- Logo Header -->
                <div class="logo-header" style="background-color:#611232">
                    <a href="@Url.Action("Index", "Home")" class="logo d-flex align-items-center">
                        <img src="~/img/logos/LOGO-SSPE.png"
                             alt="navbar brand"
                             class="navbar-brand me-2"
                             height="65" />
                    </a>
                    <div class="nav-toggle">
                        <button class="btn btn-toggle toggle-sidebar">
                            <i class="gg-menu-right"></i>
                        </button>
                        <button class="btn btn-toggle sidenav-toggler">
                            <i class="gg-menu-left"></i>
                        </button>
                    </div>
                    <button class="topbar-toggler more">
                        <i class="gg-more-vertical-alt"></i>
                    </button>
                </div>
                <!-- End Logo Header -->
            </div>
            <div class="sidebar-wrapper scrollbar scrollbar-inner">
                <div class="sidebar-content">
                    <ul class="nav nav-collapse">
                        <li class="nav-section">
                            <span class="sidebar-mini-icon">
                                <i class="fa fa-ellipsis-h"></i>
                            </span>
                            <h5 class="text-section" style="color: white">Sistema Estatal de Video Vigilancia para Particulares</h5>
                        </li>
                        <li class="mt-4">
                            <a href="@Url.Action("Index", "Casa")">
                                <span class="sub-item">Casas</span>
                            </a>
                        </li>
                        @if (User.IsInRole("SuperAdmin") || User.IsInRole("Administrador"))
                        {
                            <li class="mt-4">
                                <a href="@Url.Action("Index", "")">
                                    <span class="sub-item">Cajas</span>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Sidebar -->

        <div class="main-panel">
            <div class="main-header" style="background-color: #611232">
                <div class="main-header-logo">
                    <!-- Logo Header -->
                    <div class="logo-header" style="background-color: #611232">
                        <div class="nav-toggle">
                            <button class="btn btn-toggle toggle-sidebar">
                                <i class="gg-menu-right"></i>
                            </button>
                            <button class="btn btn-toggle sidenav-toggler">
                                <i class="gg-menu-left"></i>
                            </button>
                        </div>
                        <button class="topbar-toggler more">
                            <i class="gg-more-vertical-alt"></i>
                        </button>
                    </div>
                    <!-- End Logo Header -->
                </div>
                <!-- Navbar Header -->
                <nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
                    <div class="container-fluid">
                        <h6 class="text" style="color: white">SECRETARÍA DE SEGURIDAD PÚBLICA DE BAJA CALIFORNIA SUR</h6>

                        <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item topbar-user dropdown hidden-caret">
                                    <a class="dropdown-toggle profile-pic"
                                       data-bs-toggle="dropdown"
                                       href="#"
                                       aria-expanded="false">
                                        <div class="avatar-sm">
                                            <img src="~/img/user.png"
                                                 alt="..."
                                                 class="avatar-img rounded-circle" />
                                        </div>
                                        <span class="profile-username">
                                            <span class="op-7">Hola,</span>
                                            <span class="fw-bold"> @User.Identity.Name</span>
                                        </span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                                        <div class="dropdown-user-scroll scrollbar-outer">
                                            <li>
                                                <div class="user-box">
                                                    <div class="avatar-lg">
                                                        <img src="~/img/user.png"
                                                             alt="image profile"
                                                             class="avatar-img rounded" />
                                                    </div>
                                                    <div class="u-text">
                                                        <h4>@User.Identity.Name</h4>
                                                        <p class="text-muted">@User.FindFirst("Correo")?.Value</p>
                                                    </div>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="dropdown-divider"></div>
                                                @* <a class="dropdown-item" asp-controller="Home" asp-action="GenerarExcel">Generar Reporte de Usuario</a> *@
                                                @* <div class="dropdown-divider"></div> *@
                                                <a class="dropdown-item" asp-controller="Auth" asp-action="Logout">Cerrar sesión</a>
                                            </li>
                                        </div>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </div>
                </nav>
            <!-- End Navbar -->
        </div>

        <div class="container">
            <div class="page-inner">
                <div class="page-header">
                    @* <h4 class="page-title">@ViewData["Title"]</h4> *@
                </div>
                <div class="page-category">
                    @if (TempData["success"] != null)
                    {
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>¡Éxito!</strong> @TempData["success"]
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                    @if (TempData["error"] != null)
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>¡Error!</strong> @TempData["error"]
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                    @RenderBody()
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
                <nav class="pull-left">
                </nav>
                <div class="copyright">
                    2025, Sistema Estatal de Video Vigilancia para Particulares
                    <a href="https://sspbcs.gob.mx/ssp/">SSP</a>
                </div>
                <div>
                </div>
            </div>
        </footer>
    </div>
    <!--   Core JS Files   -->
    <script src="~/js/core/jquery-3.7.1.min.js"></script>
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/core/bootstrap.min.js"></script>

    <!-- jQuery Scrollbar -->
    <script src="~/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

    <!-- Chart JS -->
    <script src="~/js/plugin/chart.js/chart.min.js"></script>

    <!-- jQuery Sparkline -->
    <script src="~/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

    <!-- Chart Circle -->
    <script src="~/js/plugin/chart-circle/circles.min.js"></script>

    <!-- Datatables -->
    <script src="~/js/plugin/datatables/datatables.min.js"></script>

    <!-- Bootstrap Notify -->
    <script src="~/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

    <!-- jQuery Vector Maps -->
    <script src="~/js/plugin/jsvectormap/jsvectormap.min.js"></script>
    <script src="~/js/plugin/jsvectormap/world.js"></script>

    <!-- Google Maps Plugin -->
    <script src="~/js/plugin/gmaps/gmaps.js"></script>

    <!-- Sweet Alert -->
    <script src="~/js/plugin/sweetalert/sweetalert.min.js"></script>

    <!-- Kaiadmin JS -->
    <script src="~/js/kaiadmin.min.js"></script>

    <!-- sweetAlerts -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>